services:

  postgres:
    image: postgres:16
    container_name: zenfuture_postgres

    environment:
      POSTGRES_USER: zenfuture
      POSTGRES_PASSWORD: zenfuture123
      POSTGRES_DB: zenfuture_chatbot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: zenfuture_qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: